export { SettingsPage } from './SettingsPage/SettingsPage'
export { AuthPage } from './AuthPage/AuthPage'
export { PageForUnauthorized } from './PageForUnauthorized/PageForUnauthorized'
export { ProfilePage } from './ProfilePage/ProfilePage'
export { DatingPage } from './DatingPage/DatingPage'